#!/usr/bin/env ruby
# frozen_string_literal: true

require 'vkpm'

begin
  VKPM::CLI::App.start(ARGV)
rescue VKPM::Error => e
  puts e.message
rescue Interrupt
  puts 'Interrupted'
rescue HTTP::ConnectionError
  puts "Could not resolve host. Make sure it is correct, you're connected to the internet or have VPN enabled."
end
